// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ResourceManifest.proto

package mps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceManifest_StyleConfig_StyleID int32

const (
	ResourceManifest_StyleConfig__      ResourceManifest_StyleConfig_StyleID = 0
	ResourceManifest_StyleConfig_C3MM_1 ResourceManifest_StyleConfig_StyleID = 14
	ResourceManifest_StyleConfig_C3M    ResourceManifest_StyleConfig_StyleID = 15
	ResourceManifest_StyleConfig_DTM_1  ResourceManifest_StyleConfig_StyleID = 16
	ResourceManifest_StyleConfig_DTM_2  ResourceManifest_StyleConfig_StyleID = 17
	ResourceManifest_StyleConfig_C3MM_2 ResourceManifest_StyleConfig_StyleID = 52
)

// Enum value maps for ResourceManifest_StyleConfig_StyleID.
var (
	ResourceManifest_StyleConfig_StyleID_name = map[int32]string{
		0:  "_",
		14: "C3MM_1",
		15: "C3M",
		16: "DTM_1",
		17: "DTM_2",
		52: "C3MM_2",
	}
	ResourceManifest_StyleConfig_StyleID_value = map[string]int32{
		"_":      0,
		"C3MM_1": 14,
		"C3M":    15,
		"DTM_1":  16,
		"DTM_2":  17,
		"C3MM_2": 52,
	}
)

func (x ResourceManifest_StyleConfig_StyleID) Enum() *ResourceManifest_StyleConfig_StyleID {
	p := new(ResourceManifest_StyleConfig_StyleID)
	*p = x
	return p
}

func (x ResourceManifest_StyleConfig_StyleID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceManifest_StyleConfig_StyleID) Descriptor() protoreflect.EnumDescriptor {
	return file_ResourceManifest_proto_enumTypes[0].Descriptor()
}

func (ResourceManifest_StyleConfig_StyleID) Type() protoreflect.EnumType {
	return &file_ResourceManifest_proto_enumTypes[0]
}

func (x ResourceManifest_StyleConfig_StyleID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceManifest_StyleConfig_StyleID.Descriptor instead.
func (ResourceManifest_StyleConfig_StyleID) EnumDescriptor() ([]byte, []int) {
	return file_ResourceManifest_proto_rawDescGZIP(), []int{0, 1, 0}
}

type ResourceManifest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	StyleConfig   []*ResourceManifest_StyleConfig `protobuf:"bytes,2,rep,name=style_config,json=styleConfig,proto3" json:"style_config,omitempty"`
	TokenP2       string                          `protobuf:"bytes,30,opt,name=token_p2,json=tokenP2,proto3" json:"token_p2,omitempty"`
	CacheBaseUrl  string                          `protobuf:"bytes,31,opt,name=cache_base_url,json=cacheBaseUrl,proto3" json:"cache_base_url,omitempty"`
	CacheFile     []*ResourceManifest_CacheFile   `protobuf:"bytes,72,rep,name=cache_file,json=cacheFile,proto3" json:"cache_file,omitempty"`
	CacheFile_2   []string                        `protobuf:"bytes,9,rep,name=cache_file_2,json=cacheFile2,proto3" json:"cache_file_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceManifest) Reset() {
	*x = ResourceManifest{}
	mi := &file_ResourceManifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManifest) ProtoMessage() {}

func (x *ResourceManifest) ProtoReflect() protoreflect.Message {
	mi := &file_ResourceManifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManifest.ProtoReflect.Descriptor instead.
func (*ResourceManifest) Descriptor() ([]byte, []int) {
	return file_ResourceManifest_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceManifest) GetStyleConfig() []*ResourceManifest_StyleConfig {
	if x != nil {
		return x.StyleConfig
	}
	return nil
}

func (x *ResourceManifest) GetTokenP2() string {
	if x != nil {
		return x.TokenP2
	}
	return ""
}

func (x *ResourceManifest) GetCacheBaseUrl() string {
	if x != nil {
		return x.CacheBaseUrl
	}
	return ""
}

func (x *ResourceManifest) GetCacheFile() []*ResourceManifest_CacheFile {
	if x != nil {
		return x.CacheFile
	}
	return nil
}

func (x *ResourceManifest) GetCacheFile_2() []string {
	if x != nil {
		return x.CacheFile_2
	}
	return nil
}

type ResourceManifest_CacheFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceManifest_CacheFile) Reset() {
	*x = ResourceManifest_CacheFile{}
	mi := &file_ResourceManifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceManifest_CacheFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManifest_CacheFile) ProtoMessage() {}

func (x *ResourceManifest_CacheFile) ProtoReflect() protoreflect.Message {
	mi := &file_ResourceManifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManifest_CacheFile.ProtoReflect.Descriptor instead.
func (*ResourceManifest_CacheFile) Descriptor() ([]byte, []int) {
	return file_ResourceManifest_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResourceManifest_CacheFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type ResourceManifest_StyleConfig struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	UrlPrefix_1   string                               `protobuf:"bytes,1,opt,name=url_prefix_1,json=urlPrefix1,proto3" json:"url_prefix_1,omitempty"`
	UrlPrefix_2   string                               `protobuf:"bytes,9,opt,name=url_prefix_2,json=urlPrefix2,proto3" json:"url_prefix_2,omitempty"`
	StyleId       ResourceManifest_StyleConfig_StyleID `protobuf:"varint,3,opt,name=style_id,json=styleId,proto3,enum=mps.ResourceManifest_StyleConfig_StyleID" json:"style_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceManifest_StyleConfig) Reset() {
	*x = ResourceManifest_StyleConfig{}
	mi := &file_ResourceManifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceManifest_StyleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManifest_StyleConfig) ProtoMessage() {}

func (x *ResourceManifest_StyleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ResourceManifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManifest_StyleConfig.ProtoReflect.Descriptor instead.
func (*ResourceManifest_StyleConfig) Descriptor() ([]byte, []int) {
	return file_ResourceManifest_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResourceManifest_StyleConfig) GetUrlPrefix_1() string {
	if x != nil {
		return x.UrlPrefix_1
	}
	return ""
}

func (x *ResourceManifest_StyleConfig) GetUrlPrefix_2() string {
	if x != nil {
		return x.UrlPrefix_2
	}
	return ""
}

func (x *ResourceManifest_StyleConfig) GetStyleId() ResourceManifest_StyleConfig_StyleID {
	if x != nil {
		return x.StyleId
	}
	return ResourceManifest_StyleConfig__
}

var File_ResourceManifest_proto protoreflect.FileDescriptor

const file_ResourceManifest_proto_rawDesc = "" +
	"\n" +
	"\x16ResourceManifest.proto\x12\x03mps\"\x88\x04\n" +
	"\x10ResourceManifest\x12D\n" +
	"\fstyle_config\x18\x02 \x03(\v2!.mps.ResourceManifest.StyleConfigR\vstyleConfig\x12\x19\n" +
	"\btoken_p2\x18\x1e \x01(\tR\atokenP2\x12$\n" +
	"\x0ecache_base_url\x18\x1f \x01(\tR\fcacheBaseUrl\x12>\n" +
	"\n" +
	"cache_file\x18H \x03(\v2\x1f.mps.ResourceManifest.CacheFileR\tcacheFile\x12 \n" +
	"\fcache_file_2\x18\t \x03(\tR\n" +
	"cacheFile2\x1a(\n" +
	"\tCacheFile\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x1a\xe0\x01\n" +
	"\vStyleConfig\x12 \n" +
	"\furl_prefix_1\x18\x01 \x01(\tR\n" +
	"urlPrefix1\x12 \n" +
	"\furl_prefix_2\x18\t \x01(\tR\n" +
	"urlPrefix2\x12D\n" +
	"\bstyle_id\x18\x03 \x01(\x0e2).mps.ResourceManifest.StyleConfig.StyleIDR\astyleId\"G\n" +
	"\aStyleID\x12\x05\n" +
	"\x01_\x10\x00\x12\n" +
	"\n" +
	"\x06C3MM_1\x10\x0e\x12\a\n" +
	"\x03C3M\x10\x0f\x12\t\n" +
	"\x05DTM_1\x10\x10\x12\t\n" +
	"\x05DTM_2\x10\x11\x12\n" +
	"\n" +
	"\x06C3MM_2\x104B\n" +
	"Z\b/pkg/mpsb\x06proto3"

var (
	file_ResourceManifest_proto_rawDescOnce sync.Once
	file_ResourceManifest_proto_rawDescData []byte
)

func file_ResourceManifest_proto_rawDescGZIP() []byte {
	file_ResourceManifest_proto_rawDescOnce.Do(func() {
		file_ResourceManifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ResourceManifest_proto_rawDesc), len(file_ResourceManifest_proto_rawDesc)))
	})
	return file_ResourceManifest_proto_rawDescData
}

var file_ResourceManifest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ResourceManifest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ResourceManifest_proto_goTypes = []any{
	(ResourceManifest_StyleConfig_StyleID)(0), // 0: mps.ResourceManifest.StyleConfig.StyleID
	(*ResourceManifest)(nil),                  // 1: mps.ResourceManifest
	(*ResourceManifest_CacheFile)(nil),        // 2: mps.ResourceManifest.CacheFile
	(*ResourceManifest_StyleConfig)(nil),      // 3: mps.ResourceManifest.StyleConfig
}
var file_ResourceManifest_proto_depIdxs = []int32{
	3, // 0: mps.ResourceManifest.style_config:type_name -> mps.ResourceManifest.StyleConfig
	2, // 1: mps.ResourceManifest.cache_file:type_name -> mps.ResourceManifest.CacheFile
	0, // 2: mps.ResourceManifest.StyleConfig.style_id:type_name -> mps.ResourceManifest.StyleConfig.StyleID
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ResourceManifest_proto_init() }
func file_ResourceManifest_proto_init() {
	if File_ResourceManifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ResourceManifest_proto_rawDesc), len(file_ResourceManifest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ResourceManifest_proto_goTypes,
		DependencyIndexes: file_ResourceManifest_proto_depIdxs,
		EnumInfos:         file_ResourceManifest_proto_enumTypes,
		MessageInfos:      file_ResourceManifest_proto_msgTypes,
	}.Build()
	File_ResourceManifest_proto = out.File
	file_ResourceManifest_proto_goTypes = nil
	file_ResourceManifest_proto_depIdxs = nil
}
